#Forked from https://github.com/jatoben/CommandLine

matrix:
  include:
  - os: osx
    language: objective-c
    xcode_project: BitUnits.xcodeproj
    xcode_scheme: BitUnits
    script: xcodebuild -scheme BitUnits test
    osx_image: xcode9
  - os: linux
    sudo: required
    dist: trusty
    before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq clang libicu-dev
    - export SWIFT_VERSION="swift-4.0"
    - echo "Installing ${SWIFT_VERSION}..."
    - curl -s -L -O "https://swift.org/builds/${SWIFT_VERSION}-release/ubuntu1404/${SWIFT_VERSION}-RELEASE/${SWIFT_VERSION}-RELEASE-ubuntu14.04.tar.gz"
    - tar -zxvf "${SWIFT_VERSION}-RELEASE-ubuntu14.04.tar.gz"
    - sudo mv "${SWIFT_VERSION}-RELEASE-ubuntu14.04" /swift
    - export PATH="/swift/usr/bin:${PATH}"
    script:
    - swift build --verbose
    - swift test --verbose
